#include <stdio.h>
#include <math.h>
#include <time.h>

/* 
The sequence of triangle numbers is generated by adding the natural numbers. So the 
7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

Since the divisors for this problem are just the factors, we can find how many of these
there are quickly by finding the prime factors of n, and multiplying together the number
of occurances of each prime factor plus one e.g. 2*2*7 = 28, => 2 2's, 1 7 => (2+1)*(1+1)=6.

Simple brute force algorithm: 341s
Prime factor algorithm: 2s
*/

int main() {
    double time_spent = 0.0;
    clock_t begin = clock();

    int divisors = 0;
    int num = 1;
    int i = 2;
    int temp;
    int pf_powers[100000] = {0};

    // While loop until a number with 500 divisors reached
    while (divisors < 500) {
        num = num + i;
        i = i + 1;
        temp = num;

        // Find prime factors (including the number itself)
        for (long long div = 2; div <= temp; div++) {
            while (div <= temp && temp % div == 0) {
                pf_powers[div] += 1;
                temp = temp / div;
            }
        }

        // Calculate the number of divisors and reset pf_powers
        divisors = 1;
        for (int j = 0; j < 100000; j++) {
            if (pf_powers[j] > 0) {
                divisors = divisors * (pf_powers[j]+1);
                pf_powers[j] = 0;
            }
        }
    }

    printf("Solution = %li\n", num);

    clock_t end = clock();
    time_spent += (double)(end - begin) / CLOCKS_PER_SEC;
    printf("Solution found in %f seconds", time_spent);
}
