'''
How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

This one can be solved really simply with brute force and python's built in list to set casting.
For an upper bound of 100 there is no need for any optimization.
'''

terms = []

for a in range(2,101):
    for b in range(2,101):
        terms.append(a**b)

print(f"length = {len(list(set(terms)))}")